### ISSUE TITLE
Getting Mu

### ISSUE THREAD

**Issue by harensarma** [react-native-picker/picker#277]
I am getting this error:

 `Type com.reactnativecommunity.picker.BuildConfig is defined multiple times`

This is conflicting with react natives own picker with this community picker. How to uninstall the inbuilt picker or how to solve this issue .. ?

React Native version: 0.64

**Comment by PrabhakarKotipalli** [comment]
Same issue here. Found any solution till now??

**Comment by harensarma** [comment]
no.. waiting for some expert's reply :(

**Comment by harensarma** [comment]
anyone's help plz

**Comment by Raglink** [comment]
Hello @harensarma,
I had `@react-native-community/picker` and `@react-native-picker/picker` in my dependencies.
I removed `@react-native-community/picker` dependency to fix it.

**Comment by cancerberoSgx** [comment]
I'm using both libraries so I cannot solve the problem. Is there another workaround for this ?

**Comment by andrewtremblay** [comment]
@cancerberoSgx `@react-native-community/picker` and `@react-native-picker/picker` are the same libraries and the `@react-native-community/picker` location is deprecated. This can be solved by replacing references to `@react-native-community/picker` with `@react-native-picker/picker`.

**Comment by shoaibarifHWRYK** [comment]
Hello @harensarma @PrabhakarKotipalli @cancerberoSgx ,
I had @react-native-community/picker and @react-native-picker/picker in my dependencies.
I removed @react-native-community/picker dependency to fix it.
It worked for me

**Comment by shoaibarifHWRYK** [comment]
> Hello @harensarma, I had `@react-native-community/picker` and `@react-native-picker/picker` in my dependencies. I removed `@react-native-community/picker` dependency to fix it.

Thanks bro

**Comment by anthony0000** [comment]
**Raglink**, I have been on this for like a month now, only God knows how you found out that was the problem but thank you a million

**Comment by Asensio0227** [comment]
Hello.
i need help with my expo project. I encounter an error while running eas build 
Error: A runtime version is set in your AndroidManifest.xml, but is missing from your app.json/app.config.js. Please either set runtimeVersion in your app.json/app.config.js or remove expo.modules.updates.EXPO_RUNTIME_VERSION from your AndroidManifest.xml.
Error: A runtime version is set in your AndroidManifest.xml, but is missing from your app.json/app.config.js. Please either set runtimeVersion in your app.json/app.config.js or remove expo.modules.updates.EXPO_RUNTIME_VERSION from your AndroidManifest.xml.
    at setVersionsConfigAsync (/home/mthee-junior/Documents/Health-Care-v2-main/node_modules/@expo/config-plugins/build/android/Updates.js:128:11)
    at async Object.setUpdatesConfigAsync (/home/mthee-junior/Documents/Health-Care-v2-main/node_modules/@expo/config-plugins/build/android/Updates.js:122:10)
    at async syncConfigurationToNativeAndroidAsync (/home/mthee-junior/Documents/Health-Care-v2-main/node_modules/expo-updates/cli/build/syncConfigurationToNativeAsync.js:40:36)
    at async syncConfigurationToNativeAsync (/home/mthee-junior/Documents/Health-Care-v2-main/node_modules/expo-updates/cli/build/syncConfigurationToNativeAsync.js:21:13)
    at async syncConfigurationToNative (/home/mthee-junior/Documents/Health-Care-v2-main/node_modules/expo-updates/cli/build/syncConfigurationToNative.js:68:5)

i have tried locating the file i can't find it
